"""
AI Report Formatter - Parse and format AI-generated reports into rich Discord embeds.
"""
import discord
import re
from typing import Dict, Any, Optional, List
from datetime import datetime
from src.utils.formatting_utils import (
    Colors, format_number, format_percentage, format_change,
    create_standard_embed, add_standard_footer, truncate_text
)


class ReportFormatter:
    """Parse AI-generated text reports into professional Discord embeds"""
    
    def __init__(self):
        self.max_field_length = 1024
        self.max_fields = 25  # Discord limit
    
    def parse_sections(self, report_text: str) -> Dict[str, str]:
        """
        Extract sections from AI-generated markdown report.
        
        Args:
            report_text: Raw AI-generated text
            
        Returns:
            Dictionary of section_name: content
        """
        sections = {}
        
        # Match markdown headers (## Header or **Header:**)
        pattern = r'(?:##\s+|\*\*)(.*?)(?:\*\*|:)\s*\n(.*?)(?=\n(?:##|\*\*)|$)'
        matches = re.findall(pattern, report_text, re.DOTALL)
        
        for title, content in matches:
            section_name = title.strip()
            section_content = content.strip()
            sections[section_name] = section_content
        
        return sections
    
    def create_report_embed(
        self,
        title: str,
        sections: Dict[str, str],
        analytics_data: Dict[str, Any],
        guild_name: Optional[str] = None
    ) -> discord.Embed:
        """
        Create professional embed from AI report sections.
        
        Args:
            title: Report title
            sections: Parsed sections from AI report
            analytics_data: Raw analytics data for metrics
            guild_name: Server name (optional)
            
        Returns:
            Formatted Discord embed
        """
        # Create base embed
        embed = create_standard_embed(
            title=f"📊 {title}",
            description=self._create_report_header(analytics_data),
            color=Colors.PRIMARY
        )
        
        # Add metrics panel
        embed = self.add_metrics_panel(embed, analytics_data)
        
        # Add AI-generated sections as fields
        field_count = 0
        for section_name, content in sections.items():
            if field_count >= self.max_fields - 2:  # Reserve 2 for footer
                break
            
            # Skip attribution/metadata sections
            if any(skip in section_name.lower() for skip in ['generated by', 'powered by', 'serverpulse']):
                continue
            
            # Format section title with emoji
            formatted_title = self._format_section_title(section_name)
            
            # Truncate content to fit Discord limits
            formatted_content = truncate_text(content, self.max_field_length)
            
            embed.add_field(
                name=formatted_title,
                value=formatted_content,
                inline=False
            )
            field_count += 1
        
        # Add footer
        footer_text = "ServerPulse AI" + (f" • {guild_name}" if guild_name else "")
        embed.set_footer(
            text=footer_text,
            icon_url="https://raw.githubusercontent.com/twitter/twemoji/master/assets/72x72/1f4ca.png"
        )
        
        # Add thumbnail
        embed.set_thumbnail(
            url="https://raw.githubusercontent.com/twitter/twemoji/master/assets/72x72/1f4c8.png"
        )
        
        return embed
    
    def _create_report_header(self, data: Dict[str, Any]) -> str:
        """Create report header with period and key stats"""
        period = data.get('period_display', data.get('period', '24 hours'))
        start_time = data.get('start_time', '')
        end_time = data.get('end_time', '')
        
        header = f"**Period:** {period}\n"
        
        if start_time and end_time:
            try:
                start_dt = datetime.fromisoformat(start_time.replace('Z', '+00:00'))
                end_dt = datetime.fromisoformat(end_time.replace('Z', '+00:00'))
                header += f"**Analyzed:** <t:{int(start_dt.timestamp())}:d> to <t:{int(end_dt.timestamp())}:d>\n"
            except:
                pass
       
        return header
    
    def add_metrics_panel(self, embed: discord.Embed, data: Dict[str, Any]) -> discord.Embed:
        """
        Add key metrics as inline fields at the top.
        
        Args:
            embed: Embed to modify
            data: Analytics data
            
        Returns:
            Modified embed
        """
        total_messages = data.get('total_messages', 0)
        active_users = data.get('active_users', 0)
        growth_rate = data.get('growth_rate', 0)
        
        # Message count with formatting
        embed.add_field(
            name="💬 Total Messages",
            value=f"**{format_number(total_messages)}**",
            inline=True
        )
        
        # Active users
        embed.add_field(
            name="👥 Active Users",
            value=f"**{format_number(active_users)}**",
            inline=True
        )
        
        # Growth indicator
        trend_emoji = "📈" if growth_rate > 0 else "📉" if growth_rate < 0 else "➡️"
        embed.add_field(
            name=f"{trend_emoji} Growth",
            value=f"**{growth_rate:+.1f}%**",
            inline=True
        )
        
        # Member activity (if available)
        member_joins = data.get('member_joins', 0)
        member_leaves = data.get('member_leaves', 0)
        
        if member_joins > 0 or member_leaves > 0:
            net_growth = member_joins - member_leaves
            net_emoji = "✅" if net_growth > 0 else "⚠️" if net_growth < 0 else "➖"
            
            embed.add_field(
                name=f"{net_emoji} Members",
                value=f"**+{member_joins}** / **-{member_leaves}**\nNet: **{net_growth:+d}**",
                inline=True
            )
        
        return embed
    
    def add_trends_visualization(self, embed: discord.Embed, trends: Dict[str, Any]) -> discord.Embed:
        """
        Add trend indicators and comparisons.
        
        Args:
            embed: Embed to modify
            trends: Trend data
            
        Returns:
            Modified embed
        """
        from src.utils.formatting_utils import create_progress_bar
        
        if 'comparison' in trends:
            comparison = trends['comparison']
            current = comparison.get('current', 0)
            previous = comparison.get('previous', 0)
            
            change_text = format_change(current, previous)
            
            embed.add_field(
                name="📊 Trend Analysis",
                value=f"This period: **{format_number(current)}**\n"
                      f"Previous: **{format_number(previous)}**\n"
                      f"Change: **{change_text}**",
                inline=False
            )
        
        return embed
    
    def _format_section_title(self, title: str) -> str:
        """Add emoji to section titles based on keywords"""
        emoji_map = {
            'activity': '📊',
            'summary': '📝',
            'highlight': '⭐',
            'contributor': '👥',
            'growth': '📈',
            'trend': '📉',
            'insight': '💡',
            'recommendation': '✨',
            'takeaway': '🎯',
            'key': '🔑',
            'analysis': '🔍',
            'community': '👥',
            'engagement': '💬',
            'member': '👤',
        }
        
        title_lower = title.lower()
        for keyword, emoji in emoji_map.items():
            if keyword in title_lower:
                # Add emoji if not already present
                if not any(char in title for char in ['📊', '📝', '⭐', '👥', '📈', '📉', '💡', '✨', '🎯', '🔑', '🔍', '💬', '👤']):
                    return f"{emoji} {title}"
                return title
        
        return title
    
    def create_no_activity_embed(
        self,
        period: str,
        analytics_data: Dict[str, Any],
        guild_name: Optional[str] = None
    ) -> discord.Embed:
        """
        Create professional embed for periods with no activity.
        
        Args:
            period: Time period display string
            analytics_data: Analytics data (even if empty)
            guild_name: Server name (optional)
            
        Returns:
            Formatted embed
        """
        embed = create_standard_embed(
            title="📊 ServerPulse Report",
            description=f"**Period:** {period}\n**Status:** Quiet Period 🔕",
            color=Colors.NEUTRAL
        )
        
        # Member activity (if any)
        member_joins = analytics_data.get('member_joins', 0)
        member_leaves = analytics_data.get('member_leaves', 0)
        net_growth = member_joins - member_leaves
        
        if member_joins > 0 or member_leaves > 0:
            embed.add_field(
                name="👥 Member Activity",
                value=f"**New members:** {member_joins}\n"
                      f"**Members left:** {member_leaves}\n"
                      f"**Net growth:** {net_growth:+d}",
                inline=False
            )
        
        # Helpful suggestions
        embed.add_field(
            name="💡 Suggestions",
            value="• Post engaging discussion topics\n"
                  "• Share community highlights\n"
                  "• Plan interactive events\n"
                  "• Check voice channel activity",
            inline=False
        )
        
        # Possible reasons
        embed.add_field(
            name="🤔 Possible Reasons",
            value="• Natural quiet period\n"
                  "• Members in different timezones\n"
                  "• Weekend/holiday period\n"
                  "• Focus on voice channels",
            inline=False
        )
        
        # Footer
        footer_text = "ServerPulse AI" + (f" • {guild_name}" if guild_name else "")
        embed.set_footer(
            text=footer_text,
            icon_url="https://raw.githubusercontent.com/twitter/twemoji/master/assets/72x72/1f4ca.png"
        )
        
        embed.set_thumbnail(
            url="https://raw.githubusercontent.com/twitter/twemoji/master/assets/72x72/1f634.png"  # Sleeping face
        )
        
        return embed
