"""Gemini provider implementation for ServerPulse."""

import json
from typing import Dict, Any, Optional

import aiohttp

from src.ai.providers.base_provider import BaseAIProvider
from src.utils.logger import LoggerMixin


class GeminiProvider(BaseAIProvider, LoggerMixin):
    """Google Gemini provider for AI generation."""
    
    def __init__(self):
        self.base_url = "https://generativelanguage.googleapis.com/v1beta"
        self.model = "gemini-2.5-flash"  # Updated to current Gemini model
    
    async def test_connection(self, session: aiohttp.ClientSession, api_key: str) -> Dict[str, Any]:
        """Test Gemini connection."""
        test_payload = {
            "contents": [{
                "parts": [{"text": "Hello! This is a test message."}]
            }],
            "generationConfig": {
                "maxOutputTokens": 10,
                "temperature": 0.7
            }
        }
        
        try:
            async with session.post(
                f"{self.base_url}/models/{self.model}:generateContent?key={api_key}",
                json=test_payload
            ) as response:
                
                if response.status == 200:
                    data = await response.json()
                    return {
                        'success': True,
                        'model': self.model,
                        'provider': 'Google Gemini'
                    }
                else:
                    error_data = await response.text()
                    return {
                        'success': False,
                        'error': f"HTTP {response.status}: {error_data}"
                    }
                    
        except Exception as e:
            return {
                'success': False,
                'error': f"Connection error: {str(e)}"
            }
    
    async def generate_report(self, session: aiohttp.ClientSession, api_key: str,
                            analytics_data: Dict[str, Any]) -> Optional[str]:
        """Generate report using Gemini."""
        prompt = self._build_report_prompt(analytics_data)
        
        payload = {
            "contents": [{
                "parts": [{"text": prompt}]
            }],
            "generationConfig": {
                "maxOutputTokens": 1200,
                "temperature": 0.8,
                "topP": 0.8,
                "topK": 40
            }
        }
        
        try:
            async with session.post(
                f"{self.base_url}/models/{self.model}:generateContent?key={api_key}",
                json=payload
            ) as response:
                
                if response.status == 200:
                    data = await response.json()
                    
                    if 'candidates' in data and len(data['candidates']) > 0:
                        candidate = data['candidates'][0]
                        if 'content' in candidate and 'parts' in candidate['content']:
                            report = candidate['content']['parts'][0]['text'].strip()
                            
                            # Add provider attribution
                            report += "\n\n*Generated by ServerPulse AI powered by Google Gemini*"
                            
                            return report
                    
                    self.logger.error("Invalid Gemini response structure")
                    return None
                else:
                    error_text = await response.text()
                    self.logger.error(f"Gemini API error {response.status}: {error_text}")
                    return None
                    
        except Exception as e:
            self.logger.error(f"Error generating Gemini report: {e}")
            return None
    
    async def generate_insight(self, session: aiohttp.ClientSession, api_key: str,
                             analytics_data: Dict[str, Any], question: str) -> Optional[str]:
        """Generate insight using Gemini."""
        prompt = self._build_insight_prompt(analytics_data, question)
        
        payload = {
            "contents": [{
                "parts": [{"text": prompt}]
            }],
            "generationConfig": {
                "maxOutputTokens": 600,
                "temperature": 0.7,
                "topP": 0.8
            }
        }
        
        try:
            async with session.post(
                f"{self.base_url}/models/{self.model}:generateContent?key={api_key}",
                json=payload
            ) as response:
                
                if response.status == 200:
                    data = await response.json()
                    
                    if 'candidates' in data and len(data['candidates']) > 0:
                        candidate = data['candidates'][0]
                        if 'content' in candidate and 'parts' in candidate['content']:
                            insight = candidate['content']['parts'][0]['text'].strip()
                            return insight
                    
                    return None
                else:
                    error_text = await response.text()
                    self.logger.error(f"Gemini insight error {response.status}: {error_text}")
                    return None
                    
        except Exception as e:
            self.logger.error(f"Error generating Gemini insight: {e}")
            return None
