"""Grok provider implementation for ServerPulse."""

import json
from typing import Dict, Any, Optional

import aiohttp

from src.ai.providers.base_provider import BaseAIProvider
from src.utils.logger import LoggerMixin


class GrokProvider(BaseAIProvider, LoggerMixin):
    """Grok (xAI) provider for AI generation."""
    
    def __init__(self):
        self.base_url = "https://api.x.ai/v1"
        self.model = "grok-beta"
    
    async def test_connection(self, session: aiohttp.ClientSession, api_key: str) -> Dict[str, Any]:
        """Test Grok connection."""
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }
        
        test_payload = {
            "model": self.model,
            "messages": [
                {"role": "user", "content": "Hello! This is a test message."}
            ],
            "max_tokens": 10,
            "temperature": 0.7
        }
        
        try:
            async with session.post(
                f"{self.base_url}/chat/completions",
                headers=headers,
                json=test_payload
            ) as response:
                
                if response.status == 200:
                    data = await response.json()
                    return {
                        'success': True,
                        'model': self.model,
                        'provider': 'Grok (xAI)'
                    }
                else:
                    error_data = await response.text()
                    return {
                        'success': False,
                        'error': f"HTTP {response.status}: {error_data}"
                    }
                    
        except Exception as e:
            return {
                'success': False,
                'error': f"Connection error: {str(e)}"
            }
    
    async def generate_report(self, session: aiohttp.ClientSession, api_key: str,
                            analytics_data: Dict[str, Any]) -> Optional[str]:
        """Generate report using Grok."""
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }
        
        prompt = self._build_report_prompt(analytics_data)
        
        payload = {
            "model": self.model,
            "messages": [
                {
                    "role": "system",
                    "content": "You are a witty and insightful Discord community analyst who creates engaging reports for server administrators. Use Discord markdown formatting, appropriate emojis, and inject subtle humor while maintaining professionalism."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            "max_tokens": 1200,
            "temperature": 0.8
        }
        
        try:
            async with session.post(
                f"{self.base_url}/chat/completions",
                headers=headers,
                json=payload
            ) as response:
                
                if response.status == 200:
                    data = await response.json()
                    
                    if 'choices' in data and len(data['choices']) > 0:
                        report = data['choices'][0]['message']['content'].strip()
                        
                        # Add provider attribution
                        report += "\n\n*Generated by ServerPulse AI powered by Grok*"
                        
                        return report
                    else:
                        self.logger.error("No choices in Grok response")
                        return None
                else:
                    error_text = await response.text()
                    self.logger.error(f"Grok API error {response.status}: {error_text}")
                    return None
                    
        except Exception as e:
            self.logger.error(f"Error generating Grok report: {e}")
            return None
    
    async def generate_insight(self, session: aiohttp.ClientSession, api_key: str,
                             analytics_data: Dict[str, Any], question: str) -> Optional[str]:
        """Generate insight using Grok."""
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }
        
        prompt = self._build_insight_prompt(analytics_data, question)
        
        payload = {
            "model": self.model,
            "messages": [
                {
                    "role": "system",
                    "content": "You are a Discord community expert with a knack for finding patterns and providing actionable insights. Be direct, data-driven, and occasionally witty in your analysis."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            "max_tokens": 600,
            "temperature": 0.7
        }
        
        try:
            async with session.post(
                f"{self.base_url}/chat/completions",
                headers=headers,
                json=payload
            ) as response:
                
                if response.status == 200:
                    data = await response.json()
                    
                    if 'choices' in data and len(data['choices']) > 0:
                        insight = data['choices'][0]['message']['content'].strip()
                        return insight
                    else:
                        return None
                else:
                    error_text = await response.text()
                    self.logger.error(f"Grok insight error {response.status}: {error_text}")
                    return None
                    
        except Exception as e:
            self.logger.error(f"Error generating Grok insight: {e}")
            return None
